language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap
install:
- ./travis-tool.sh install_deps
- Rscript -e 'if (!require("covr")) devtools::install_github("kirillseva/covr")'
- Rscript -e 'if (!require("testthat")) devtools::install_github("hadley/testthat")'
- Rscript -e 'if (!require("testthatsomemore")) devtools::install_github("robertzk/testthatsomemore")'
script: ./travis-tool.sh run_tests
after_failure:
- ./travis-tool.sh dump_logs
after_success:
  - "Rscript -e 'library(covr);coveralls()'"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: KUVsut8WOTbytie+wbMY/TqPjz4ItuOcVWWHzedCPVOKVHZgcCNLNvhlCC1aODBHXW0mik6e1Y2XMXqTmihtN+OBrqagfXIqLA/EURS75BNJt36WOMpxMNAXF2MbeFPQ2ICKjzqOQQMKNPu+uKp7RTQEn292ctRoF6SQXDq33/8=
    on_success: change
    on_failure: change
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}'
env:
- global:
  - WARNINGS_ARE_ERRORS=1
  - _R_CHECK_FORCE_SUGGESTS_=0
